<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit397376fa97f86cf42f8d2e1f56d3fb31
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MediaRonLLC\\QuotesDLXThemes\\' => 28,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MediaRonLLC\\QuotesDLXThemes\\' => 
        array (
            0 => __DIR__ . '/../..' . '/',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit397376fa97f86cf42f8d2e1f56d3fb31::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit397376fa97f86cf42f8d2e1f56d3fb31::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit397376fa97f86cf42f8d2e1f56d3fb31::$classMap;

        }, null, ClassLoader::class);
    }
}
